### ISSUE TITLE
Do we need the AccessLint bot?

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/mario#12]
I'm not sure there will be anything for it to review in this project. Can we disable it? Is there a reason we should keep it?

**Comment by JPrevost** [comment]
In order to turn it off for this repo, we'd have to give it a list of repos to check rather than saying "everything in the org". If we do that, we'd have to remember to add it on new repositories as they are added. I am confident we'd forget to do that on something it should be enabled on. My preference is to just leave it on, but I definitely acknowledge that it's kinda pointless for this repo.

**Comment by gravesm** [comment]
Yeah, that's cool. I thought there might be something like this. It's fine.
